// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHhc3nl0_TJq6orB2tNuXstbRShDcf8tU',
    appId: '1:658413954501:web:e686bbb19e06c1c86157ac',
    messagingSenderId: '658413954501',
    projectId: 'flutter-notes-96f0b',
    authDomain: 'flutter-notes-96f0b.firebaseapp.com',
    storageBucket: 'flutter-notes-96f0b.appspot.com',
    measurementId: 'G-7DZ9QZ0WE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBXf1qEmglXiqMsuvWyjc3jWU5zG1yu90',
    appId: '1:658413954501:android:900e4ef84752cdbc6157ac',
    messagingSenderId: '658413954501',
    projectId: 'flutter-notes-96f0b',
    storageBucket: 'flutter-notes-96f0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9Qe3NhgctX0EoW2enNX2f4No87LqN8E',
    appId: '1:658413954501:ios:9401f420116c2d066157ac',
    messagingSenderId: '658413954501',
    projectId: 'flutter-notes-96f0b',
    storageBucket: 'flutter-notes-96f0b.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe9Qe3NhgctX0EoW2enNX2f4No87LqN8E',
    appId: '1:658413954501:ios:9401f420116c2d066157ac',
    messagingSenderId: '658413954501',
    projectId: 'flutter-notes-96f0b',
    storageBucket: 'flutter-notes-96f0b.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHhc3nl0_TJq6orB2tNuXstbRShDcf8tU',
    appId: '1:658413954501:web:94dc4ac8fd6b82136157ac',
    messagingSenderId: '658413954501',
    projectId: 'flutter-notes-96f0b',
    authDomain: 'flutter-notes-96f0b.firebaseapp.com',
    storageBucket: 'flutter-notes-96f0b.appspot.com',
    measurementId: 'G-MJ8ZKRY5B2',
  );
}
